// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs471q3H0_XF04O4w9WmkuACAMnLxNTPM',
    appId: '1:767976103345:web:403927d44a2d8d8452b190',
    messagingSenderId: '767976103345',
    projectId: 'pettinder-fcfaa',
    authDomain: 'pettinder-fcfaa.firebaseapp.com',
    storageBucket: 'pettinder-fcfaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_30KKkiDaOdNbHGy0qhXCgZlSXhnXUb4',
    appId: '1:767976103345:android:5d0cc3635837cc0d52b190',
    messagingSenderId: '767976103345',
    projectId: 'pettinder-fcfaa',
    storageBucket: 'pettinder-fcfaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcdXa7hqHdo0Gbd9gmvkftMtpQL0UH0A0',
    appId: '1:767976103345:ios:42baa71dcb9c7e5352b190',
    messagingSenderId: '767976103345',
    projectId: 'pettinder-fcfaa',
    storageBucket: 'pettinder-fcfaa.appspot.com',
    iosClientId: '767976103345-7jjbhel617kbvoo1r536u6okrs6or2g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.petTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcdXa7hqHdo0Gbd9gmvkftMtpQL0UH0A0',
    appId: '1:767976103345:ios:42baa71dcb9c7e5352b190',
    messagingSenderId: '767976103345',
    projectId: 'pettinder-fcfaa',
    storageBucket: 'pettinder-fcfaa.appspot.com',
    iosClientId: '767976103345-7jjbhel617kbvoo1r536u6okrs6or2g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.petTinder',
  );
}
